# server:
#   port: 8191
# spring:
#   cloud:
#     config:
#       server:
#         git:
#           uri: https://github.com/sasankaviraj/spring-cloud-config
#           search-paths:
#            - '*service'



