spring:
  application:
    name: book-service   #bootstrap.yml runs before application.yml
    
server:
  port: 0 #randomly select the port

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
